name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Supabase environment files
        run: |
          # Create module version for Investment Odyssey
          cat > activities/investment-odyssey/js/services/env.js << EOF
          export const supabaseUrl = '${{ secrets.SUPABASE_URL }}';
          export const supabaseKey = '${{ secrets.SUPABASE_ANON_KEY }}';
          EOF

          # Create non-module version for other pages
          cat > js/env.js << EOF
          const supabaseUrl = '${{ secrets.SUPABASE_URL }}';
          const supabaseKey = '${{ secrets.SUPABASE_ANON_KEY }}';
          EOF

          echo "Supabase environment files created successfully."

      - name: Update select-section.html
        run: |
          if [ -f select-section.html ]; then
            # Use perl instead of sed for better handling of special characters
            perl -i -pe "s|(const supabaseUrl = )[^;]*;|\1'${{ secrets.SUPABASE_URL }}';|" select-section.html
            perl -i -pe "s|(const supabaseKey = )[^;]*;|\1'${{ secrets.SUPABASE_ANON_KEY }}';|" select-section.html
            echo "Updated select-section.html with Supabase credentials"
          else
            echo "Warning: select-section.html not found"
          fi

          # Update the supabase-config.js file to use the env.js file
          cat > activities/investment-odyssey/js/services/supabase-config.js << EOF
          /**
           * Supabase Configuration for Investment Odyssey
           *
           * This file initializes Supabase and exports the client.
           */

          // Import the Supabase client
          import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.38.4/+esm';
          import { supabaseUrl, supabaseKey } from './env.js';

          // Create Supabase client
          const supabase = createClient(supabaseUrl, supabaseKey);

          // Export the client
          export default supabase;
          EOF

          echo "Supabase configuration updated successfully."

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          token: ${{ secrets.DEPLOY_TOKEN }}
          branch: gh-pages
