name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Replace Supabase credentials
        run: |
          # Create module version for Investment Odyssey
          cat > activities/investment-odyssey/js/services/env.js << EOF
          export const supabaseUrl = '${{ secrets.SUPABASE_URL }}';
          export const supabaseKey = '${{ secrets.SUPABASE_ANON_KEY }}';
          EOF

          # Create non-module version for other pages
          cat > js/env.js << EOF
          const supabaseUrl = '${{ secrets.SUPABASE_URL }}';
          const supabaseKey = '${{ secrets.SUPABASE_ANON_KEY }}';
          EOF

          # Replace hardcoded credentials in select-section.html
          sed -i "s|const supabaseUrl = 'https://clyyjcjwcbbmdlccmtaa.supabase.co';|const supabaseUrl = '${{ secrets.SUPABASE_URL }}';|g" select-section.html
          sed -i "s|const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNseXlqY2p3Y2JibWRsY2NtdGFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NTk3NDQsImV4cCI6MjA2MDQzNTc0NH0.ADHB7McgJ29pMWmLgjMZYiU9Tnk2ZodKvf4PBndmxbQ';|const supabaseKey = '${{ secrets.SUPABASE_ANON_KEY }}';|g" select-section.html

          # Verify the files were created (without showing the actual values)
          echo "Supabase environment files created successfully."

          # Update the supabase-config.js file to use the env.js file
          cat > activities/investment-odyssey/js/services/supabase-config.js << EOF
          /**
           * Supabase Configuration for Investment Odyssey
           *
           * This file initializes Supabase and exports the client.
           */

          // Import the Supabase client
          import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.38.4/+esm';
          import { supabaseUrl, supabaseKey } from './env.js';

          // Create Supabase client
          const supabase = createClient(supabaseUrl, supabaseKey);

          // Export the client
          export default supabase;
          EOF

          echo "Supabase configuration updated successfully."

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          token: ${{ secrets.DEPLOY_TOKEN }}
          branch: gh-pages
